import type { AuthProvider } from '../auth/index.js';
import { AuthError, errorForStatus } from './errors.js';

export interface TransportOptions {
  baseUrl: string;
  auth: AuthProvider;
  /** Defaults to the global `fetch`. */
  fetch?: typeof fetch;
}

export interface RequestOptions {
  method?: string;
  query?: Record<string, string | number | boolean | undefined>;
  /** JSON body, or a FormData for multipart. */
  body?: unknown;
  signal?: AbortSignal;
}

/**
 * Thin fetch wrapper: auth header, query building, error normalization, and a
 * single retry after a 401.
 *
 * The 401 retry exists because a session token can expire between being read
 * from cache and reaching the hub. It retries EXACTLY once, after invalidating
 * the cached credential — a loop here would turn a revoked key into a hot spin
 * against the auth endpoint.
 */
export class HttpTransport {
  private readonly baseUrl: string;
  private readonly auth: AuthProvider;
  private readonly fetchImpl: typeof fetch;

  constructor(opts: TransportOptions) {
    this.baseUrl = opts.baseUrl.replace(/\/+$/, '');
    this.auth = opts.auth;
    const impl = opts.fetch ?? globalThis.fetch;
    if (!impl) {
      throw new Error('No fetch implementation available — pass one via `fetch` (Node < 18).');
    }
    // `.bind` is load-bearing in browsers: calling `this.fetchImpl(...)` with an
    // unbound `globalThis.fetch` invokes it with the transport as its receiver,
    // and the DOM implementation rejects that with "Illegal invocation". Node's
    // fetch is indifferent to its receiver, so this fails ONLY in a browser.
    this.fetchImpl = impl.bind(globalThis);
  }

  async request<T>(path: string, opts: RequestOptions = {}): Promise<T> {
    const res = await this.send(path, opts, false);
    return this.parse<T>(res);
  }

  private async send(path: string, opts: RequestOptions, isRetry: boolean): Promise<Response> {
    const url = new URL(`${this.baseUrl}${path}`);
    for (const [k, v] of Object.entries(opts.query ?? {})) {
      if (v !== undefined) url.searchParams.set(k, String(v));
    }

    const isForm = typeof FormData !== 'undefined' && opts.body instanceof FormData;
    const headers: Record<string, string> = {
      authorization: `Bearer ${await this.auth.getHeaderToken()}`,
    };
    // Never set Content-Type for multipart: the boundary is generated by the
    // runtime and setting it by hand produces an unparseable body.
    if (opts.body !== undefined && !isForm) headers['content-type'] = 'application/json';

    const res = await this.fetchImpl(url.toString(), {
      method: opts.method ?? 'GET',
      headers,
      body: opts.body === undefined ? undefined : isForm ? (opts.body as FormData) : JSON.stringify(opts.body),
      signal: opts.signal,
    });

    // One retry only, and only for a credential that can actually be refreshed.
    if (res.status === 401 && !isRetry) {
      this.auth.invalidate();
      const refreshed = await this.auth.getHeaderToken().catch(() => null);
      if (refreshed) return this.send(path, opts, true);
    }

    return res;
  }

  private async parse<T>(res: Response): Promise<T> {
    if (res.status === 204) return undefined as T;

    const text = await res.text();
    let body: unknown = undefined;
    if (text) {
      try {
        body = JSON.parse(text);
      } catch {
        body = text;
      }
    }

    if (!res.ok) {
      const retryAfterHeader = res.headers.get('retry-after');
      const retryAfter = retryAfterHeader ? Number(retryAfterHeader) : null;
      throw errorForStatus(res.status, body, Number.isFinite(retryAfter) ? retryAfter : null);
    }

    return body as T;
  }

  /** For the WS layer: the credential that may legally appear in a URL. */
  async queryToken(): Promise<string> {
    const token = await this.auth.getQueryToken();
    if (!token) {
      throw new AuthError(
        'This credential cannot be used to open a WebSocket from a browser. ' +
          'An API key must stay server-side — exchange it for a session token.',
      );
    }
    return token;
  }

  get origin(): string {
    return this.baseUrl;
  }
}
